mame_directory: /home/yumry/mame/
mame_executable: mame
mame_args: -output network
roms_directory: /home/yumry/mame/roms/
resolution_x: 1680
resolution_y: 1050
fps_limit: 244
ui_scaling: 0.4
font_size: 70
mouse_sensitivity: 2
key_bindings:
  start:
  - 65293
  - btn_start
  left:
  - 65361
  - 97
  - dpad_l
  right:
  - 65363
  - 100
  - dpad_r
  up:
  - 65362
  - 119
  - dpad_u
  down:
  - 65364
  - 115
  - dpad_d
  settings:
  - 32
  - btn_y
  delete:
  - 65535
  close_mame:
  - btn_leftshoulder
  - btn_rightshoulder
