mame_directory: /home/yumry/mame
mame_executable: mame
mame_args: -output network
roms_directory: /home/yumry/mame/roms
resolution_x: 1920
resolution_y: 1080
fullscreen: true
enable_vsync: false
fps_limit: 120
ui_scaling: 0.4
font_size: 70
mouse_sensitivity: 2
native_linux_joysticks: false
native_joystick_device: /dev/input/js1
key_bindings:
  start:
  - 65293
  - btn_start
  - btn_b
  left:
  - 65361
  - 97
  - dpad_l
  - 65515
  right:
  - 65363
  - 100
  - dpad_r
  up:
  - 65362
  - 119
  - dpad_u
  down:
  - 65364
  - 115
  - dpad_d
  - 65307
  settings:
  - 32
  - btn_y
  delete:
  - 65535
  close_mame: []
