mame_directory: /home/yumry/mame/
mame_executable: mame
mame_args: -output network
roms_directory: /home/yumry/mame/roms/
resolution_x: 1680
resolution_y: 1050
fps_limit: 244
ui_scaling: 0.4
font_size: 70
mouse_sensitivity: 2
key_bindings:
  start:
  - 65293
  left:
  - 65361
  - 97
  right:
  - 65363
  - 100
  up:
  - 65362
  - 119
  down:
  - 65364
  - 115
  settings:
  - 32
  delete:
  - 65535
